### ISSUE TITLE
Config travis for running builds

### ISSUE THREAD

**Issue by denar90** [marionettejs/marionette-integrations#13]
I think we need travis here to run build all example which we have here. It will be easy to check if new changes don't break anything. 
We already have [travis.yaml](https://github.com/marionettejs/marionette-integrations/blob/master/.travis.yml) but need to add 
```
env:
  - secure:
```
to run `travis-runner.sh`

@samccone can you take care of this?

**Comment by paulfalgout** [comment]
I turned travis on for this repo, so the next PR should trigger it.  I'm not entirely sure what you're wanting to add to the env.  I think everything should run now without changes to the yaml?

**Comment by denar90** [comment]
Cool. 👍 
About changes to yaml file. I was trying to run it in my fork but got error `/home/travis/build.sh: line 45: ./travis-runner.sh: Permission denied`
https://travis-ci.org/denar90/marionette-integrations/jobs/132510763
I think travis needs secure key to run some scripts.

**Comment by denar90** [comment]
fixed by #17
