### ISSUE TITLE
webpack.config.js modulesDirectories issue

### ISSUE THREAD

**Issue by lvv83** [marionettejs/marionette-integrations#30]
Hello.

I try use integration with webpack. During build process I got next error:

> ERROR in ./~/backbone.marionette/lib/backbone.marionette.js
Module not found: Error: Cannot resolve module 'backbone.radio' in C:\data\coding\mjs\node_modules\backbone.marionette\lib
 @ ./~/backbone.marionette/lib/backbone.marionette.js 12:133-158

After some researching I found this line in **webpack.config.js**
```javascript
 resolve: {
   modulesDirectories: [path.join(__dirname, './node_modules')],
   root: path.join(__dirname, './app')
  }
```

Webpack [documentation](https://webpack.github.io/docs/configuration.html#resolve-modulesdirectories) says that 
> Just use a directory name, not a path. Use only if you expect to have a hierarchy within these folders

Then I deleted `modulesDirectories` property, and after this build the project with success

**Comment by denar90** [comment]
Looks like missed `backbone.radio` in dependencies.

**Comment by denar90** [comment]
@lvv83 which version of node are you using?

**Comment by lvv83** [comment]
Node version 4.4.4

**Comment by denar90** [comment]
with node v6 it looks fine....
@lvv83 would you like to open PR with your changes?

**Comment by lvv83** [comment]
Please, see PR #32
Just test it with Node 6.4.0 - no problems
