### ISSUE TITLE
stylus-loader for webpack

### ISSUE THREAD

**Issue by lvv83** [marionettejs/marionette-integrations#34]
Hello. Yet one question about webpack integration.

How should we use [stylus-loader](https://www.npmjs.com/package/stylus-loader)?
There is nor plugin definition in `webpack.config.js` nor files with `styl` extension.

So may be [this](https://github.com/marionettejs/marionette-integrations/blob/master/webpack/package.json#L31) dependency unnecessary?

**Comment by denar90** [comment]
I think `style-loader` from [config](https://github.com/marionettejs/marionette-integrations/blob/master/webpack/webpack.config.js#L29)  needs `stylus-loader`as dependency.

**Comment by denar90** [comment]
You are right, good find, so sure `stylus-loader` can be removed from deps.
