### ISSUE TITLE
the webpack integration project build script erro

### ISSUE THREAD

**Issue by isikfsc** [marionettejs/marionette-integrations#42]
hi,

in the webpack2 and probably webpack sub projects the package.json scripts include bash invocation of eslint and webpack, for example in the build script. however the project does not install them globally so as to bash have them s commands.

`npm run lint && webpack -p` as `lint` there resolves to`eslint app` invocation. however It does not work. I think this is due to I do not have eslint as a command on my shell. I try in the bash
`$eslint` and get command not found, same for the webpack.

when I `npm install -g webpack`, for exampe, I do not get the error for it as I have taken before, I think it will be same for the eslint, as well.

However, this seems to conflict with the behaviour that the `webpack-dev-server --open` can work even it is not available as a bash command, and I have not installed it globally only locally with npm install from  inside the webpack2 dir.

Any insigths into this?

**Comment by isikfsc** [comment]
I think the npm docs explain this here [https://docs.npmjs.com/misc/scripts#path](https://docs.npmjs.com/misc/scripts#path)

**Comment by jeffreycahyono** [comment]
It seems you've encountered the same problem with #46 .
Best practice now is install eslint and webpack locally not global. If you want to call eslint locally just enter node module's local bin to the PATH env, before execute eslint, using this command `export PATH=$PATH:./node_modules/.bin/`
