### ISSUE TITLE
Browserify possible without global jQuery?

### ISSUE THREAD

**Issue by braznaavtrav** [marionettejs/marionette-integrations#7]
Currently in the example integration, jQuery is loaded separate from the built javascript file and then used at a global level. Is this absolutely necessary? Or is there a way to use it more seamlessly with Browserify?

**Comment by denar90** [comment]
Closing this one because of new examples. Now it fixed https://github.com/marionettejs/marionette-integrations/blob/master/browserify/vendor/vendor.js
